### ISSUE TITLE
Get ship's image?

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [LeNitrous/Nimi#6]
I found this repo accidentally from my Github's feed, and it's interesting. I'm trying to make an app for it, but how can I get the ship's image?

**Comment by LeNitrous** [comment]
The API is purely for game data only although we are planning on hosting images sometime. I can't assure you when though. Right now the only way is to host extracted game data by yourself. Certain endpoint responses a key named `assetName`, `icon`, or `painting`. These direct you to the images being used.

I'll leave this issue open for tracking.

**Comment by sr229** [comment]
Marking wontfix, you should handle the assets yourself for now.
